# Generated by Django 5.0.6 on 2024-06-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_book_isbn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="id",
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                max_length=13, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
